name: bright
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  dartz: ^0.10.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  fluttertoast: ^8.2.10
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  go_router: ^14.6.3
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.3.5
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif-VariableFont_wdth,wght.ttf
    - family: NunitoSans
      fonts:
        - asset: assets\fonts\NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: app_assets.dart